### ISSUE TITLE
大佬，后台账号密码不正确

### ISSUE THREAD

**Issue by Tine789** [convee/goblog#22]

**Comment by convee** [comment]
用户名密码可以改user表，密码生成规则在项目中有对应的测试用例
<img width="1056" alt="image" src="https://github.com/convee/goblog/assets/35790774/90167bf9-cf6b-4473-b6f6-9695b1ba4daf">

**Comment by Tine789** [comment]
> 用户名密码可以改user表，密码生成规则在项目中有对应的测试用例 <img alt="image" width="1056" src="https://user-images.githubusercontent.com/35790774/268487459-90167bf9-cf6b-4473-b6f6-9695b1ba4daf.png">

我改了账号和密码，搭建好之后界面不一样，用来一段时间，总体上还行，建议优化下UI，还有就是不支持markdown，建议支持下

**Comment by convee** [comment]
> > 用户名密码可以改user表，密码生成规则在项目中有对应的测试用例 <img alt="image" width="1056" src="https://user-images.githubusercontent.com/35790774/268487459-90167bf9-cf6b-4473-b6f6-9695b1ba4daf.png">
> 
> 我改了账号和密码，搭建好之后界面不一样，用来一段时间，总体上还行，建议优化下UI，还有就是不支持markdown，建议支持下

前后端都支持呀，是不是哪里配置有问题，可以看看演示站：https://convee.cn
<img width="1212" alt="image" src="https://github.com/convee/goblog/assets/35790774/7997b6ba-d8ad-40ef-a206-ca2b21b28820">
<img width="968" alt="image" src="https://github.com/convee/goblog/assets/35790774/963f4dd0-f4a3-414a-a32e-d62f1334e1af">

**Comment by Tine789** [comment]
为啥我们不一样[image](https://github.com/convee/goblog/assets/87940618/e3fa6999-b754-4051-a10b-894f67985ccd)

**Comment by Tine789** [comment]
![image](https://github.com/convee/goblog/assets/87940618/5e37b4d6-e3e3-4114-8d1d-8aba664a379f)

**Comment by Tine789** [comment]
配置肯定出了问题，但是我不知道在哪

**Comment by convee** [comment]
> ![image](https://user-images.githubusercontent.com/87940618/269237712-5e37b4d6-e3e3-4114-8d1d-8aba664a379f.png)

看起来像是静态资源没有加载出来，右键看下源码，或者f12看下浏览器报错信息

**Comment by Tine789** [comment]
> > ![image](https://user-images.githubusercontent.com/87940618/269237712-5e37b4d6-e3e3-4114-8d1d-8aba664a379f.png)
> 
> 看起来像是静态资源没有加载出来，右键看下源码，或者f12看下浏览器报错信息
看到了，静态资源地址不对，在哪里改，大佬

**Comment by Tine789** [comment]
> > > ![image](https://user-images.githubusercontent.com/87940618/269237712-5e37b4d6-e3e3-4114-8d1d-8aba664a379f.png)
> > 
> > 
> > 看起来像是静态资源没有加载出来，右键看下源码，或者f12看下浏览器报错信息
> > 看到了，静态资源地址不对，在哪里改，大佬

ok了

**Comment by Tine789** [comment]
![image](https://github.com/convee/goblog/assets/87940618/7010c5aa-cf93-4c1a-8500-15439d12d6c8)
正常了，感觉自己像傻逼样

**Comment by convee** [comment]
> ![image](https://user-images.githubusercontent.com/87940618/269338664-7010c5aa-cf93-4c1a-8500-15439d12d6c8.png) 正常了，感觉自己像傻逼样

还有很多不完善的地方，有空一起完善下

**Comment by Tine789** [comment]
好的
